#!/usr/bin/env python3
"""Generate uncompressed LVGL 4-bpp Noto CJK subset from UI source text."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import re
root = Path(__file__).resolve().parents[1]
font_path = '/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc'
font = ImageFont.truetype(font_path, 24, index=2)
chars = set(chr(i) for i in range(32, 127))
for p in root.rglob('*.c'):
    if 'assets' not in p.parts:
        for literal in re.findall(r'"((?:[^"\\]|\\.)*)"', p.read_text()):
            chars.update(c for c in literal if ord(c) >= 127)
chars = sorted(chars, key=ord)
bitmap = []
glyphs = [(0, 0, 0, 0, 0, 0)]
for char in chars:
    left, top, right, bottom = font.getbbox(char, anchor='ls')
    width, height = right-left, bottom-top
    im = Image.new('L', (max(1,width), max(1,height)))
    ImageDraw.Draw(im).text((-left,-top), char, font=font, fill=255, anchor='ls')
    pixels = [round(v/17) for v in im.getdata()] if width*height else []
    start = len(bitmap)
    for i in range(0, len(pixels), 2):
        bitmap.append((pixels[i]<<4) | (pixels[i+1] if i+1 < len(pixels) else 0))
    glyphs.append((start,round(font.getlength(char)*16),width,height,left,-bottom))
lines=['/* Generated by tools/make_font.py. Noto Sans CJK, SIL OFL 1.1. */',
       '#include <lvgl/lvgl.h>', 'static const uint8_t bitmap[] = {']
for i in range(0,len(bitmap),24): lines.append(','.join(map(str,bitmap[i:i+24]))+',')
lines += ['};','static const lv_font_fmt_txt_glyph_dsc_t glyphs[] = {']
for idx,adv,w,h,x,y in glyphs:
    lines.append(f'{{.bitmap_index={idx},.adv_w={adv},.box_w={w},.box_h={h},.ofs_x={x},.ofs_y={y}}},')
lines += ['};','static const uint16_t unicode_list[] = {',','.join(str(ord(c)-32) for c in chars),'};',
'''static const lv_font_fmt_txt_cmap_t cmaps[] = {
 {.range_start=32, .range_length='''+str(ord(chars[-1])-31)+''', .glyph_id_start=1,
  .unicode_list=unicode_list, .glyph_id_ofs_list=NULL,
  .list_length='''+str(len(chars))+''', .type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}
};
static lv_font_fmt_txt_dsc_t dsc = {
 .glyph_bitmap=bitmap, .glyph_dsc=glyphs, .cmaps=cmaps,
 .kern_dsc=NULL, .kern_scale=0, .cmap_num=1, .bpp=4,
 .kern_classes=0, .bitmap_format=0
};
const lv_font_t desktop_font = {
 .get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,
 .get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,
 .line_height=36, .base_line=7, .dsc=&dsc,
 .underline_position=-3, .underline_thickness=1
};''']
(root/'assets/desktop_font.c').write_text('\n'.join(lines)+'\n')
print(f'Generated {len(chars)} glyphs, {len(bitmap)} bitmap bytes')
