#!/usr/bin/env python3
"""Generate uncompressed LVGL 4-bpp Noto CJK subset from UI source text."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import re
root = Path(__file__).resolve().parents[1]
source_roots = [root, root.parent / 'fallguard', root.parent / 'photo_identify']
font_path = '/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc'
font = ImageFont.truetype(font_path, 24, index=2)
chars = set(chr(i) for i in range(32, 127))
for source_root in source_roots:
    for p in source_root.rglob('*.c'):
        if 'assets' not in p.parts:
            for literal in re.findall(r'"((?:[^"\\]|\\.)*)"', p.read_text()):
                chars.update(c for c in literal if ord(c) >= 127)
# PC object descriptions need more than the fixed UI literals.
# Include the GB2312 repertoire (common simplified Chinese + punctuation).
for high in range(0xa1, 0xf8):
    for low in range(0xa1, 0xff):
        try:
            chars.add(bytes([high, low]).decode('gb2312'))
        except UnicodeDecodeError:
            pass
chars = sorted(chars, key=ord)
# LV_FONT_FMT_TXT_LARGE=0 uses a 20-bit bitmap_index. Keep each
# fallback bank well below 1 MiB without changing the global LVGL ABI.
BANK_LIMIT = 512 * 1024
banks = []
bitmap = []
glyphs = [(0, 0, 0, 0, 0, 0)]
bank_chars = []
for char in chars:
    left, top, right, bottom = font.getbbox(char, anchor='ls')
    width, height = right-left, bottom-top
    im = Image.new('L', (max(1,width), max(1,height)))
    ImageDraw.Draw(im).text((-left,-top), char, font=font, fill=255, anchor='ls')
    pixels = [round(v/17) for v in im.getdata()] if width*height else []
    packed = [(pixels[i]<<4) | (pixels[i+1] if i+1 < len(pixels) else 0)
              for i in range(0, len(pixels), 2)]
    if bitmap and len(bitmap) + len(packed) > BANK_LIMIT:
        banks.append((bank_chars, bitmap, glyphs))
        bitmap, bank_chars = [], []
        glyphs = [(0, 0, 0, 0, 0, 0)]
    start = len(bitmap)
    bitmap.extend(packed)
    advance = round(font.getlength(char)*16)
    assert start < (1 << 20) and advance < (1 << 12)
    assert 0 <= width <= 255 and 0 <= height <= 255
    assert -128 <= left <= 127 and -128 <= -bottom <= 127
    glyphs.append((start,advance,width,height,left,-bottom))
    bank_chars.append(char)
banks.append((bank_chars, bitmap, glyphs))
lines = ['/* Generated by tools/make_font.py. Noto Sans CJK, SIL OFL 1.1. */',
         '#include <lvgl/lvgl.h>']
for bank in reversed(range(len(banks))):
    subset, bitmap, glyphs = banks[bank]
    prefix = f'bank_{bank}'
    first = ord(subset[0])
    lines.append(f'static const uint8_t {prefix}_bitmap[] = {{')
    for i in range(0,len(bitmap),24):
        lines.append(','.join(map(str,bitmap[i:i+24]))+',')
    lines += ['};', f'static const lv_font_fmt_txt_glyph_dsc_t {prefix}_glyphs[] = {{']
    for idx,adv,w,h,x,y in glyphs:
        lines.append(f'{{.bitmap_index={idx},.adv_w={adv},.box_w={w},.box_h={h},.ofs_x={x},.ofs_y={y}}},')
    lines += ['};', f'static const uint16_t {prefix}_unicode[] = {{',
              ','.join(str(ord(c)-first) for c in subset), '};',
              f'static const lv_font_fmt_txt_cmap_t {prefix}_cmaps[] = {{',
              f'{{.range_start={first},.range_length={ord(subset[-1])-first+1},.glyph_id_start=1,',
              f'.unicode_list={prefix}_unicode,.glyph_id_ofs_list=NULL,',
              f'.list_length={len(subset)},.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}}', '};',
              f'static lv_font_fmt_txt_dsc_t {prefix}_dsc = {{',
              f'.glyph_bitmap={prefix}_bitmap,.glyph_dsc={prefix}_glyphs,.cmaps={prefix}_cmaps,',
              '.kern_dsc=NULL,.kern_scale=0,.cmap_num=1,.bpp=4,.kern_classes=0,.bitmap_format=0', '};']
    name = 'desktop_font' if bank == 0 else f'desktop_font_bank_{bank}'
    linkage = '' if bank == 0 else 'static '
    fallback = 'NULL' if bank + 1 == len(banks) else f'&desktop_font_bank_{bank+1}'
    lines += [f'{linkage}const lv_font_t {name} = {{',
              '.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,',
              '.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,',
              f'.line_height=36,.base_line=7,.dsc=&{prefix}_dsc,.fallback={fallback},',
              '.underline_position=-3,.underline_thickness=1', '};']
(root/'assets/desktop_font.c').write_text('\n'.join(lines)+'\n')
print(f'Generated {len(chars)} glyphs in {len(banks)} banks; bytes per bank: ' +
      ', '.join(str(len(b[1])) for b in banks))
